### ISSUE TITLE
Unable to install the plugin

### ISSUE THREAD

**Issue by manikandan-bambus** [approov/quickstart-ionic-advancedhttp#1]
I have tried to install the plugin as per the docs **https://ionicframework.com/docs/native/approov-advanced-http**, I can't install the plugin. And I have a question, why ionic (open source project) move towards paid plugins?

**Comment by jexh** [comment]
Hi there,
On Mon, 14 Mar 2022 at 14:57, manikandan-bambus ***@***.***>
wrote:

> I have tried to install the plugin as per the docs *https://ionicframework.com/docs/native/approov-advanced-http
> <https://ionicframework.com/docs/native/approov-advanced-http>*, I can't
> install the plugin.
>
We want to help solve this issue. Contacting Approov support directly (
***@***.***) providing more details about what you did and how it
failed will help us address this issue.

> And I have a question, why ionic (open source project) move towards paid
> plugins?
>
To clarify on this question, Approov is completely unaffiliated with Ionic.
Approov is a SaaS mobile app security service and, as part of our product
offering, we attempt to make integration easy with whatever frontend and
backend technologies you use for your app development. The Ionic plugin is
a part of that provision. Approov is not free, but it is value for money;
the costs scale with the load on our backend systems and are inline with
the success of your apps. The service has a primary cloud component
operating in multiple geographic regions with full redundancy and
auto-scaling to cope with fluctuations in load and there is a failover
system to handle requests if the primary system fails. Most importantly,
the service is supported by a dedicated team of engineers constantly
working to improve the product and update it to defend against the latest
threats in the mobile space. There is a 30-day free trial to evaluate
Approov in the context of your project requirements.

**Comment by richardmtaylor** [comment]
Hi there,

Please can you provide more details so that we can help you with this
problem?

Are you following the Approov Ionic quickstart guide (
https://github.com/approov/quickstart-ionic-advancedhttp)?

Do you have an active Approov trial, or are you trying to do the
integration before starting a trial?

Thanks,
Jae
